/**
 * Phrase-tone overrides replicating pypinyin's phrase-dict behavior.
 *
 * The training data was prepared with pypinyin, whose built-in phrase
 * dictionary applies natural readings for common phrases (一定 -> yi2,
 * 不是 -> bu2, 觉得 -> jue2 de5, ...) without tone_sandhi. The browser
 * frontend must reproduce those readings to stay on the model's training
 * distribution. Regenerate with: python scripts/mine_phrase_tones.py
 * (top 300 by BZNSYP corpus frequency).
 */

export const PHRASE_TONE_OVERRIDES: Record<string, string[]> = {
  '一个': ['yi2', 'ge4'],
  '这个': ['zhe4', 'ge5'],
  '不是': ['bu2', 'shi4'],
  '一点': ['yi4', 'dian3'],
  '一起': ['yi4', 'qi3'],
  '认为': ['ren4', 'wei2'],
  '一直': ['yi4', 'zhi2'],
  '不会': ['bu2', 'hui4'],
  '不要': ['bu2', 'yao4'],
  '成为': ['cheng2', 'wei2'],
  '觉得': ['jue2', 'de5'],
  '部分': ['bu4', 'fen4'],
  '要求': ['yao1', 'qiu2'],
  '一定': ['yi2', 'ding4'],
  '银行': ['yin2', 'hang2'],
  '会儿': ['hui4', 'er5'],
  '似乎': ['si4', 'hu1'],
  '妻子': ['qi1', 'zi3'],
  '了解': ['liao3', 'jie3'],
  '不到': ['bu2', 'dao4'],
  '那个': ['na4', 'ge5'],
  '一只': ['yi1', 'zhi1'],
  '不了': ['bu4', 'liao3'],
  '作为': ['zuo4', 'wei2'],
  '一百': ['yi4', 'bai3'],
  '一场': ['yi1', 'chang2'],
  '是不是': ['shi4', 'bu2', 'shi4'],
  '几乎': ['ji1', 'hu1'],
  '头发': ['tou2', 'fa4'],
  '当天': ['dang4', 'tian1'],
  '照片': ['zhao4', 'pian1'],
  '行业': ['hang2', 'ye4'],
  '不住': ['bu2', 'zhu4'],
  '行为': ['xing2', 'wei2'],
  '以为': ['yi3', 'wei2'],
  '一会儿': ['yi1', 'hui4', 'er5'],
  '一般': ['yi4', 'ban1'],
  '为主': ['wei2', 'zhu3'],
  '作坊': ['zuo1', 'fang5'],
  '女子': ['nv3', 'zi3'],
  '意思': ['yi4', 'si5'],
  '爪子': ['zhua3', 'zi5'],
  '弟弟': ['di4', 'di5'],
  '都会': ['du1', 'hui4'],
  '反应': ['fan3', 'ying4'],
  '漂白': ['piao3', 'bai2'],
  '目的': ['mu4', 'di4'],
  '称为': ['cheng1', 'wei2'],
  '肮脏': ['ang1', 'zang1'],
  '不见': ['bu2', 'jian4'],
  '参与': ['can1', 'yu4'],
  '肚子': ['du3', 'zi5'],
  '音乐': ['yin1', 'yue4'],
  '仔细': ['zi3', 'xi4'],
  '处理': ['chu3', 'li3'],
  '姥姥': ['lao3', 'lao5'],
  '少年': ['shao4', 'nian2'],
  '折腾': ['zhe1', 'teng5'],
  '显得': ['xian3', 'de5'],
  '答应': ['da1', 'ying4'],
  '便宜': ['pian2', 'yi5'],
  '扫帚': ['sao4', 'zhou3'],
  '晕倒': ['yun1', 'dao3'],
  '查查': ['zha1', 'zha1'],
  '漂亮': ['piao4', 'liang4'],
  '调整': ['tiao2', 'zheng3'],
  '劲儿': ['jin4', 'er5'],
  '参差': ['cen1', 'ci1'],
  '哪个': ['na3', 'ge5'],
  '回应': ['hui2', 'ying4'],
  '处于': ['chu3', 'yu2'],
  '妥当': ['tuo3', 'dang4'],
  '婆婆': ['po2', 'po5'],
  '宁愿': ['ning4', 'yuan4'],
  '当晚': ['dang4', 'wan3'],
  '揣测': ['chuai3', 'ce4'],
  '晃晃': ['huang4', 'huang4'],
  '高兴': ['gao1', 'xing4'],
  '一半': ['yi2', 'ban4'],
  '一度': ['yi2', 'du4'],
  '倔强': ['jue2', 'jiang4'],
  '动弹': ['dong4', 'tan2'],
  '嚷嚷': ['rang1', 'rang5'],
  '央行': ['yang1', 'hang2'],
  '干净': ['gan1', 'jing4'],
  '应对': ['ying4', 'dui4'],
  '应用': ['ying4', 'yong4'],
  '攒动': ['cuan2', 'dong4'],
  '模样': ['mu2', 'yang4'],
  '王子': ['wang2', 'zi3'],
  '蛤蟆': ['ha2', 'ma5'],
  '记得': ['ji4', 'de5'],
  '起哄': ['qi3', 'hong4'],
  '重庆': ['chong2', 'qing4'],
  '重新': ['chong2', 'xin1'],
  '一旦': ['yi2', 'dan4'],
  '一面': ['yi2', 'mian4'],
  '为人': ['wei2', 'ren2'],
  '人为': ['ren2', 'wei2'],
  '冠军': ['guan4', 'jun1'],
  '协调': ['xie2', 'tiao2'],
  '卷土重来': ['juan3', 'tu3', 'chong2', 'lai2'],
  '呕吐': ['ou3', 'tu4'],
  '哥们儿': ['ge1', 'men5', 'er5'],
  '子女': ['zi3', 'nv3'],
  '家伙': ['jia1', 'huo5'],
  '干嘛': ['gan4', 'ma2'],
  '懂得': ['dong3', 'de5'],
  '成都': ['cheng2', 'du1'],
  '扁担': ['bian3', 'dan4'],
  '更为': ['geng4', 'wei2'],
  '极为': ['ji2', 'wei2'],
  '查处': ['cha2', 'chu3'],
  '着急': ['zhao2', 'ji2'],
  '窝囊': ['wo1', 'nang1'],
  '类似': ['lei4', 'si4'],
  '蛮横': ['man2', 'heng4'],
  '进一步': ['jin4', 'yi2', 'bu4'],
  '遇难': ['yu4', 'nan4'],
  '一向': ['yi2', 'xiang4'],
  '一致': ['yi2', 'zhi4'],
  '不对': ['bu2', 'dui4'],
  '倒是': ['dao3', 'shi4'],
  '值得': ['zhi2', 'de5'],
  '傀儡': ['kui3', 'lei3'],
  '兴趣': ['xing4', 'qu4'],
  '别扭': ['bie4', 'niu3'],
  '勉强': ['mian3', 'qiang3'],
  '干吗': ['gan4', 'ma2'],
  '应急': ['ying4', 'ji2'],
  '应酬': ['ying4', 'chou2'],
  '执拗': ['zhi2', 'niu4'],
  '扫把': ['sao4', 'ba3'],
  '拗不过': ['niu4', 'bu4', 'guo4'],
  '摇晃': ['yao2', 'huang4'],
  '父子': ['fu4', 'zi3'],
  '睡觉': ['shui4', 'jiao4'],
  '空调': ['kong1', 'tiao2'],
  '船只': ['chuan2', 'zhi1'],
  '茄子': ['qie2', 'zi5'],
  '角色': ['jue2', 'se4'],
  '记载': ['ji4', 'zai3'],
  '诸葛': ['zhu1', 'ge3'],
  '逮捕': ['dai4', 'bu3'],
  '铺盖': ['pu1', 'gai4'],
  '长发': ['chang2', 'fa4'],
  '长期': ['chang2', 'qi1'],
  '首都': ['shou3', 'du1'],
  '一代': ['yi2', 'dai4'],
  '一宿': ['yi1', 'xiu3'],
  '不见了': ['bu2', 'jian4', 'le5'],
  '为止': ['wei2', 'zhi3'],
  '为生': ['wei2', 'sheng1'],
  '关卡': ['guan1', 'qia3'],
  '分子': ['fen4', 'zi3'],
  '十一点': ['shi2', 'yi4', 'dian3'],
  '厦门': ['xia4', 'men2'],
  '参差不齐': ['cen1', 'ci1', 'bu4', 'qi2'],
  '受不了': ['shou4', 'bu4', 'liao3'],
  '大部分': ['da4', 'bu4', 'fen4'],
  '好意思': ['hao3', 'yi4', 'si5'],
  '差不多': ['cha4', 'bu5', 'duo1'],
  '摔倒': ['shuai1', 'dao3'],
  '明了': ['ming2', 'liao3'],
  '漂洗': ['piao3', 'xi3'],
  '率先': ['shuai4', 'xian1'],
  '番茄': ['fan1', 'qie2'],
  '疑似': ['yi2', 'si4'],
  '石头': ['shi2', 'tou5'],
  '笼罩': ['long3', 'zhao4'],
  '累累': ['lei3', 'lei3'],
  '藏獒': ['zang4', 'ao2'],
  '试卷': ['shi4', 'juan4'],
  '重复': ['chong2', 'fu4'],
  '钻石': ['zuan4', 'shi2'],
  '长江': ['chang2', 'jiang1'],
  '骨头': ['gu3', 'tou5'],
  '不一样': ['bu4', 'yi2', 'yang4'],
  '了事': ['liao3', 'shi4'],
  '亮相': ['liang4', 'xiang4'],
  '佛山': ['fo2', 'shan1'],
  '使得': ['shi3', 'de5'],
  '供应': ['gong1', 'ying4'],
  '冗长': ['rong3', 'chang2'],
  '判处': ['pan4', 'chu3'],
  '反弹': ['fan3', 'tan2'],
  '咧咧': ['lie1', 'lie1'],
  '国都': ['guo2', 'du1'],
  '处罚': ['chu3', 'fa2'],
  '好奇': ['hao4', 'qi2'],
  '宿舍': ['su4', 'she4'],
  '少女': ['shao4', 'nv3'],
  '当铺': ['dang4', 'pu4'],
  '悄然': ['qiao3', 'ran2'],
  '成分': ['cheng2', 'fen4'],
  '所得': ['suo3', 'de5'],
  '打的': ['da3', 'di1'],
  '投奔': ['tou2', 'ben4'],
  '指头': ['zhi3', 'tou5'],
  '挣扎': ['zheng1', 'zha2'],
  '散发': ['san4', 'fa4'],
  '更新': ['geng1', 'xin1'],
  '歌曲': ['ge1', 'qu3'],
  '淹没': ['yan1', 'mo4'],
  '照相': ['zhao4', 'xiang4'],
  '爱好': ['ai4', 'hao4'],
  '理发': ['li3', 'fa4'],
  '疑为': ['yi2', 'wei2'],
  '疙瘩': ['ge1', 'da5'],
  '的士': ['di1', 'shi4'],
  '的当': ['di2', 'dang4'],
  '相应': ['xiang1', 'ying4'],
  '着眼': ['zhuo2', 'yan3'],
  '睡着': ['shui4', 'zhao2'],
  '给予': ['ji3', 'yu3'],
  '老将': ['lao3', 'jiang4'],
  '若干': ['ruo4', 'gan1'],
  '落下': ['la4', 'xia4'],
  '行当': ['hang2', 'dang1'],
  '裁缝': ['cai2', 'feng2'],
  '谁都': ['shei2', 'dou1'],
  '调控': ['tiao2', 'kong4'],
  '调试': ['tiao2', 'shi4'],
  '躺倒': ['tang3', 'dao3'],
  '辗转': ['zhan3', 'zhuan3'],
  '邋遢': ['la1', 'ta1'],
  '都市': ['du1', 'shi4'],
  '金发': ['jin1', 'fa4'],
  '阿胶': ['e1', 'jiao1'],
  '一分钟': ['yi4', 'fen1', 'zhong1'],
  '一口气': ['yi4', 'kou3', 'qi4'],
  '一幕': ['yi2', 'mu4'],
  '下调': ['xia4', 'tiao2'],
  '中毒': ['zhong4', 'du2'],
  '了不起': ['liao3', 'bu4', 'qi3'],
  '佛教': ['fo2', 'jiao4'],
  '供奉': ['gong4', 'feng4'],
  '倒在地上': ['dao3', 'zai4', 'di4', 'shang4'],
  '假期': ['jia4', 'qi1'],
  '充分': ['chong1', 'fen4'],
  '出差': ['chu1', 'chai1'],
  '切磋': ['qie1', 'cuo1'],
  '势头': ['shi4', 'tou5'],
  '单杠': ['dan1', 'gang4'],
  '压轴': ['ya1', 'zhou4'],
  '发网': ['fa4', 'wang3'],
  '同行': ['tong2', 'hang2'],
  '君子': ['jun1', 'zi3'],
  '呛人': ['qiang4', 'ren2'],
  '呼吁': ['hu1', 'yu4'],
  '哽咽': ['geng3', 'ye4'],
  '商量': ['shang1', 'liang2'],
  '在行': ['zai4', 'hang2'],
  '好学': ['hao4', 'xue2'],
  '婀娜': ['e1', 'nuo2'],
  '媳妇儿': ['xi2', 'fu4', 'er5'],
  '少林': ['shao4', 'lin2'],
  '尾巴': ['wei3', 'ba5'],
  '干脆': ['gan1', 'cui4'],
  '当作': ['dang4', 'zuo4'],
  '恶心': ['e3', 'xin1'],
  '拧紧': ['ning3', 'jin3'],
  '揣摩': ['chuai3', 'mo2'],
  '散文': ['san3', 'wen2'],
  '数落': ['shu3', 'luo4'],
  '暑假': ['shu3', 'jia4'],
  '曝光': ['bao4', 'guang1'],
  '有空': ['you3', 'kong4'],
  '杠杆': ['gang4', 'gan3'],
  '来得': ['lai2', 'de5'],
  '标的': ['biao1', 'di4'],
  '没收': ['mo4', 'shou1'],
  '流血': ['liu2', 'xie3'],
  '济南': ['ji3', 'nan2'],
  '琢磨': ['zhuo2', 'mo2'],
  '瑜伽': ['yu2', 'jia1'],
  '的确': ['di2', 'que4'],
  '相似': ['xiang1', 'si4'],
  '相处': ['xiang1', 'chu3'],
  '相机': ['xiang4', 'ji1'],
  '看不见': ['kan4', 'bu2', 'jian4'],
  '看中': ['kan4', 'zhong4'],
  '看守': ['kan1', 'shou3'],
  '看守所': ['kan1', 'shou3', 'suo3'],
  '着手': ['zhuo2', 'shou3'],
  '着风': ['zhao2', 'feng1'],
  '知了': ['zhi1', 'liao3'],
  '短发': ['duan3', 'fa4'],
  '种地': ['zhong4', 'di4'],
  '种花': ['zhong4', 'hua1'],
  '簸箕': ['bo4', 'ji1'],
  '胡同': ['hu2', 'tong4'],
  '舌头': ['she2', 'tou5'],
  '蚂蚱': ['ma4', 'zha4'],
  '蚌埠': ['beng4', 'bu4'],
  '西藏': ['xi1', 'zang4'],
  '要得': ['yao4', 'de5'],
  '调解': ['tiao2', 'jie3'],
  '质的': ['zhi4', 'di4'],
  '跟斗': ['gen1', 'dou3'],
};
